backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "cv_data"
    label: "Data Portofolio & CV"
    folder: "data"
    create: false
    fields:
      - {label: "Judul Halaman", name: "title", widget: "string"}
      - {label: "Nama Lengkap", name: "nama", widget: "string"}
      - {label: "Deskripsi Singkat / Bio", name: "bio", widget: "text"}
      - {label: "Keahlian (Skills)", name: "skills", widget: "list", summary: "{{fields.title}}"}
