backend:
  name: github
  repo: whoisbagaskr/My-Portofolio
  branch: main
  base_url: https://decap-cms-oauth-provider.vercel.app
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "cv_data"
    label: "Data Portofolio & CV"
    folder: "data"
    create: false
    fields:
      - {label: "Nama Lengkap", name: "nama", widget: "string"}
      - {label: "Tagline", name: "tagline", widget: "string"}
      - {label: "Ringkasan Tentang Saya", name: "ringkasan", widget: "text"}
