backend:
  name: github
  repo: whoisbagaskr/My-Portofolio
  branch: main
  base_url: https://decap-cms-oauth-provider.vercel.app
  auth_endpoint: api/auth
  client_id: Ov23li3toYeOpIDmUJQK
  client_secret: 52666cdbdedf74bc5b9baaf574012184113de8b6

media_folder: "images"
public_folder: "/images"

collections:
  - name: "cv_data"
    label: "Data Portofolio & CV"
    folder: "data"
    create: false
    fields:
      - {label: "Judul Halaman", name: "title", widget: "string"}
      - {label: "Nama Lengkap", name: "nama", widget: "string"}
      - {label: "Deskripsi Singkat / Bio", name: "bio", widget: "text"}
      - {label: "Keahlian (Skills)", name: "skills", widget: "list", summary: "{{fields.title}}"}
